version: '3.4'

services:
  smarttripplanner.sample:
    image: ${DOCKER_REGISTRY-}smarttripplannersample
    build:
      context: .
      dockerfile: src/SmartTripPlanner.Sample/Dockerfile
    environment:
      - RedisOptions__Host=smarttripplanner.redis:6379
      - RedisOptions__InstanceName=SmartTripPlanner-

  smarttripplanner.redis:
    image: redis/redis-stack:latest
    container_name: smarttripplanner.redis
    restart: no
    volumes:
      - ./.containers/smarttripplanner.redis:/data
    ports:
      - 6379:6379
      - 8001:8001
