version: '3.4'

services:
  smarttripplanner.sample:
    image: ${DOCKER_REGISTRY-}smarttripplannersample
    build:
      context: .
      dockerfile: src/SmartTripPlanner.Sample/Dockerfile
    env_file:
      - .env

  smarttripplanner.redis:
    image: redis/redis-stack:latest
    container_name: smarttripplanner.redis
    restart: no
    volumes:
      - ./.containers/smarttripplanner.redis:/data
    ports:
      - 6379:6379
      - 8001:8001
